services:
  hoge-app-1:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file:
      - .env
    ports:
      - 6061:8080
    volumes:
      - .:/go/app
    networks:
      - hoge-network-1

networks:
  hoge-network-1:
    external: true
